name: Feature request
description: Suggest an improvement to mdfier.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem should this solve?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What would you like to happen?
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      multiple: true
      options:
        - Firefox
        - Chrome
